import os
import glob

def main():
    asset_dir = "../colormaps"
    output_file = os.path.join("..", "include", "termimage_colormaps.h")

    files = sorted(glob.glob(os.path.join(asset_dir, "*.bin")))

    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    with open(output_file, "w") as out:
        out.write("// AUTO-GENERATED by colormaps/embed_assets.py -- do not edit\n")
        out.write("#ifndef TERMIMAGE_COLORMAPS_H\n")
        out.write("#define TERMIMAGE_COLORMAPS_H\n\n")
        out.write("namespace termimage {\n")
        out.write("namespace detail {\n\n")

        names = []
        for f in files:
            name = os.path.splitext(os.path.basename(f))[0]
            names.append(name)
            var_name = f"CMAP_{name.upper()}"

            with open(f, "rb") as binary_file:
                data = binary_file.read()

            out.write(f"// {name} ({len(data) // 3} entries)\n")
            out.write(f"static const unsigned char {var_name}[] = {{")

            for i, byte in enumerate(data):
                if i % 16 == 0:
                    out.write("\n    ")
                out.write(f"0x{byte:02x},")
                if i % 16 != 15:
                    out.write(" ")

            out.write("\n};\n\n")

        # Write count constant
        out.write(f"static const int CMAP_COUNT = {len(names)};\n\n")

        # Write name array
        out.write("static const char* const CMAP_NAMES[] = {\n")
        for name in names:
            out.write(f'    "{name}",\n')
        out.write("};\n\n")

        # Write data pointer array (same order as CMAP_NAMES)
        out.write("static const unsigned char* const CMAP_DATA[] = {\n")
        for name in names:
            out.write(f"    CMAP_{name.upper()},\n")
        out.write("};\n\n")

        out.write("} // namespace detail\n")
        out.write("} // namespace termimage\n\n")
        out.write("#endif // TERMIMAGE_COLORMAPS_H\n")

    print(f"Generated {output_file} with {len(names)} colormaps: {', '.join(names)}")

if __name__ == "__main__":
    main()
