import os
import tempfile

COLORMAPS = [
    "viridis",
    "plasma",
    "inferno",
    "magma",
    "cividis",
    "coolwarm",
    "gnuplot",
    "turbo",
]


def load_colormap_bytes(name):
    os.environ.setdefault(
        "MPLCONFIGDIR", os.path.join(tempfile.gettempdir(), "termimage-matplotlib")
    )
    try:
        import matplotlib
    except ImportError as exc:
        raise RuntimeError(
            "matplotlib is required to generate termimage_colormaps.h"
        ) from exc

    cmap = matplotlib.colormaps[name].resampled(256)
    data = []
    for i in range(256):
        rgba = cmap(i)
        for channel in rgba[:3]:
            data.append(max(0, min(255, int(round(channel * 255.0)))))
    return data


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    output_file = os.path.join(repo_root, "include", "termimage_colormaps.h")

    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    with open(output_file, "w") as out:
        out.write("// AUTO-GENERATED by scripts/generate_colormaps.py -- do not edit\n")
        out.write("#ifndef TERMIMAGE_COLORMAPS_H\n")
        out.write("#define TERMIMAGE_COLORMAPS_H\n\n")
        out.write("#include <array>\n")
        out.write("#include <cstdint>\n\n")
        out.write("namespace termimage {\n")
        out.write("namespace detail {\n\n")

        for name in COLORMAPS:
            var_name = f"CMAP_{name.upper()}"
            data = load_colormap_bytes(name)

            if len(data) != 768:
                raise ValueError(f"{name} must generate exactly 768 bytes")

            out.write(f"// {name} ({len(data) // 3} entries)\n")
            out.write(f"static const std::array<std::uint8_t, 768> {var_name} = {{{{")

            for i, byte in enumerate(data):
                if i % 16 == 0:
                    out.write("\n    ")
                out.write(f"0x{byte:02x},")
                if i % 16 != 15:
                    out.write(" ")

            out.write("\n}};\n\n")

        out.write("} // namespace detail\n")
        out.write("} // namespace termimage\n\n")
        out.write("#endif // TERMIMAGE_COLORMAPS_H\n")

    print(
        f"Generated {output_file} with {len(COLORMAPS)} colormaps: "
        f"{', '.join(COLORMAPS)}"
    )


if __name__ == "__main__":
    main()
